FROM golang:1.21.10 AS go_builder

ENV GO111MODULE=on \
    CGO_ENABLED=0 \
    GOOS=linux \
    GOARCH=amd64 \
    GOPROXY=https://goproxy.cn,direct

WORKDIR /app
COPY . .
RUN go mod tidy
RUN go build -o demo .

FROM alpine:3.9.6
RUN sed -i -e 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories

ENV TZ Asia/Shanghai
RUN apk add tzdata


COPY --from=go_builder /app/http/demo /demo
COPY --from=go_builder /app/http/demo/etc/env.yaml /etc/env.yaml


EXPOSE 8000
ENTRYPOINT ["./demo"]
